-- ====================================
-- SCRIPT DE INICIALIZAÇÃO DO BANCO DE DADOS
-- API de Consulta de Créditos
-- ====================================

-- Criar a tabela de créditos
CREATE TABLE IF NOT EXISTS credito (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_credito VARCHAR(50) NOT NULL,
    numero_nfse VARCHAR(50) NOT NULL,
    data_constituicao DATE NOT NULL,
    valor_issqn DECIMAL(15, 2) NOT NULL,
    tipo_credito VARCHAR(50) NOT NULL,
    simples_nacional BOOLEAN NOT NULL,
    aliquota DECIMAL(5, 2) NOT NULL,
    valor_faturado DECIMAL(15, 2) NOT NULL,
    valor_deducao DECIMAL(15, 2) NOT NULL,
    base_calculo DECIMAL(15, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Criar índices para melhorar performance das consultas
CREATE INDEX IF NOT EXISTS idx_credito_numero_nfse ON credito (numero_nfse);
CREATE INDEX IF NOT EXISTS idx_credito_numero_credito ON credito (numero_credito);
CREATE INDEX IF NOT EXISTS idx_credito_data_constituicao ON credito (data_constituicao);
CREATE INDEX IF NOT EXISTS idx_credito_tipo_credito ON credito (tipo_credito);

-- Comentários para documentação
COMMENT ON TABLE credito IS 'Tabela de créditos constituídos para consulta via API';
COMMENT ON COLUMN credito.id IS 'Identificador único do crédito';
COMMENT ON COLUMN credito.numero_credito IS 'Número identificador do crédito constituído';
COMMENT ON COLUMN credito.numero_nfse IS 'Número identificador da NFS-e';
COMMENT ON COLUMN credito.data_constituicao IS 'Data da constituição do crédito';
COMMENT ON COLUMN credito.valor_issqn IS 'Valor do ISSQN do crédito';
COMMENT ON COLUMN credito.tipo_credito IS 'Tipo do crédito (ISSQN, Outros, etc.)';
COMMENT ON COLUMN credito.simples_nacional IS 'Indica se é enquadrado no Simples Nacional';
COMMENT ON COLUMN credito.aliquota IS 'Alíquota aplicada ao crédito';
COMMENT ON COLUMN credito.valor_faturado IS 'Valor total faturado';
COMMENT ON COLUMN credito.valor_deducao IS 'Valor de dedução aplicado';
COMMENT ON COLUMN credito.base_calculo IS 'Base de cálculo do crédito';
COMMENT ON COLUMN credito.created_at IS 'Data e hora de criação do registro';
COMMENT ON COLUMN credito.updated_at IS 'Data e hora da última atualização do registro'; 